server:
  port: 8088

netty:
  host: 0.0.0.0
  port: 7397

#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp

# 定位模板的目录
#spring.mvc.view.prefix=classpath:/templates/
# 给返回的页面添加后缀名
#spring.mvc.view.suffix=.html
